name: voice_app
description: A cross-platform Flutter application for ASR and TTS using sherpa-onnx.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.3
  path: ^1.9.0
  record: ^6.1.2
  audioplayers: ^5.0.0
  sherpa_onnx:
    path: ../sherpa-onnx/flutter/sherpa_onnx
  opus_mt_macos:
    path: ../opus_mt/flutter/opus_mt_macos
  llamacpp_macos:
    path: ../llama/flutter/llamacpp_macos
  voice_engine_macos:
    path: ../voice_engine/flutter/voice_engine_macos
  simulst_macos:
    path: ../simulst/flutter/simulst_macos
  file_picker: ^11.0.2
  archive: ^4.0.9
  ffi: ^2.1.0
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
    image_path: "assets/app_icon_macos.png"
  web:
    generate: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/espeak-ng-data.zip
    - assets/silero_vad.onnx
